### ISSUE TITLE
responsive landscape mode

### ISSUE THREAD

**Issue by visualmanipulator** [MAU-COLLECTIVE/suboi-next.js#74]
landscape is not working

<img width="736" alt="Bildschirmfoto 2021-06-03 um 22 17 37" src="https://user-images.githubusercontent.com/69480779/120706597-96a01700-c4b9-11eb-9f60-12ab61318521.png">

**Comment by anbeangry** [comment]
I think it's hard to adapt this on right breakpoint. For mobile

**Comment by visualmanipulator** [comment]
hm what should we do then if the user for example turns the phone?
