### ISSUE TITLE
wrong red color

### ISSUE THREAD

**Issue by visualmanipulator** [MAU-COLLECTIVE/suboi-next.js#78]
this is the right red color
#FF3434

pls change all red elements to this color

**Comment by anbeangry** [comment]
Red colors is on point

**Comment by visualmanipulator** [comment]
it looks different for me here
this is on web rn
<img width="797" alt="Bildschirmfoto 2021-06-04 um 21 21 15" src="https://user-images.githubusercontent.com/69480779/120852690-d418a900-c57a-11eb-9400-60fa4cda3b89.png">

this is in xd
<img width="657" alt="Bildschirmfoto 2021-06-04 um 21 20 44" src="https://user-images.githubusercontent.com/69480779/120852715-dd097a80-c57a-11eb-87c0-d74484fe0b9f.png">

or does xd show the colours diff? how about #ff0000 this is like the pure red now
